corn <- read.table("/scratch/mentors/dbuckmas/corn_data.txt", header = TRUE, sep = "\t", fill = TRUE)
field_corn <- subset(corn, COMMODITY_DESC == 'CORN')
IN_field_corn <- subset(field_corn, STATE_NAME == 'INDIANA')
IN2010_weather <- read.table("/scratch/mentors/dbuckmas/1063091.csv", header = TRUE, sep = ",", fill = TRUE)
IN_corn2010 <- subset(IN_field_corn, YEAR == '2010')
corn_acresharvested2010 <- subset(IN_corn2010, SHORT_DESC == 'CORN, GRAIN - ACRES HARVESTED')
corn_acresplanted2010 <- subset(IN_corn2010, SHORT_DESC == 'CORN - ACRES PLANTED')
county_corn_harvested2010 <- subset(corn_acresharvested2010, AGG_LEVEL_DESC == 'COUNTY')
county_corn_planted2010 <- subset(corn_acresplanted2010, AGG_LEVEL_DESC == 'COUNTY')
tapply(county_corn_harvested2010$VALUE,county_corn_harvested2010$COUNTY_NAME,print)
print(county_corn_planted2010$COUNTY_NAME)
county_corn_harvested2010$COUNTY_NAME <- factor(county_corn_harvested2010$COUNTY_NAME)
